Repository shuttle-hq/shuttle, pull requests merged in 2023-07, with the labels that each got.

#1074 chore: bump tower-sanitize-path
  Cargo.lock
  gateway/Cargo.toml
Labels: A-gateway

#1075 fix: broken gateway pagination and status check tests
  gateway/src/api/latest.rs
  gateway/src/service.rs
Labels: A-gateway

#1084 feat: resource recorder
  .circleci/config.yml
  Cargo.lock
  Cargo.toml
  codegen/Cargo.toml
  common-tests/Cargo.toml
  common-tests/src/lib.rs
  common/src/backends/auth.rs
  common/src/claims.rs
  proto/resource-recorder.proto
  proto/src/generated/resource_recorder.rs
  proto/src/lib.rs
  proto/tests/bootstrap.rs
  provisioner/Cargo.toml
  provisioner/src/lib.rs
  resource-recorder/Cargo.toml
  resource-recorder/migrations/0000_init.sql
  resource-recorder/src/args.rs
  resource-recorder/src/dal.rs
  resource-recorder/src/lib.rs
  resource-recorder/src/main.rs
  resource-recorder/src/type/database.rs
  resource-recorder/src/type/mod.rs
  resource-recorder/tests/integration_tests.rs
Labels: L

#1082 Added the missing support for creating custom resources
  common/src/models/resource.rs
  common/src/resource.rs
  deployer/src/persistence/mod.rs
  deployer/src/persistence/resource/mod.rs
  resource-recorder/src/type/mod.rs
  service/src/lib.rs
Labels: XS, A-resources

#1109 circleci: set HONEYCOMB env variable
  .circleci/config.yml
Labels: XS

#1087 fix: Update information in README
  README.md
Labels: XS

#1093 chore: fix Actix Web typos
  README.md
  cargo-shuttle/src/args.rs
  runtime/README.md
Labels: XS

#1098 fix(codegen): allow `main` function name, prevent clippy warning
  codegen/src/shuttle_main/mod.rs
  codegen/tests/ui/main/duplicate-main-fn.rs
  codegen/tests/ui/main/duplicate-main-fn.stderr
  runtime/src/alpha/mod.rs
Labels: S, A-codegen

#1077 feat: Handling regular signals sent to cargo-shuttle on Windows
  cargo-shuttle/src/lib.rs
Labels: S
